### ISSUE TITLE
Filepath in output

### ISSUE THREAD

**Issue by lauritssn** [whitesource/jninka#6]
Given I am a JNinka user
When I run JNinka on a large project
Then the XML output contains no information about the path of the file a license is found in.

Would it be possible to include the path of the file somehow? It's really hard to use the output for anything sensible without the path information of the files.

**Comment by sschuberth** [comment]
FYI, I've addressed this issue in my fork. I'll happily merge it back (along with other improvements) once my preparing PR #7 got accepted.
